# Generated by Django 5.2.4 on 2025-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nowpayments_sub_partner_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
